title: Marco-Bolo Data Lab
longtitle: The Lab Space for the [Marco-Bolo Project](https://marcobolo-project.eu)
email: info@marcobolo-project.eu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MARCOBOLO_EU
github_username:  marco-bolo

# Build settings
remote_theme: sighingnow/jekyll-gitbook
plugins:
  - jekyll-feed
  - jemoji

favicon_path:  assets/marco-bolo/img/cropped-MARCO-BOLO_logo_col-32x32.png

#  from theme gitbook:
## markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     colourful # rouge
  syntax_highlighter_opts:
    guess_lang:           true

## syntax highlighting
syntax_highlighter_style: colorful

## enable toc
toc:
    enabled: true
    h_min: 1
    h_max: 3

permalink: /:categories/:year-:month-:day-:title:output_ext

collections:
  pages:
    output: true
    permalink: /:collection/:path/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _drafts
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
